### ISSUE TITLE
Authentication redirect not working

### ISSUE THREAD

**Issue by pdunkerley** [dotnet/systemweb-adapters#195]
I am having issues getting the redirect to the login page to work when accessing a Core page when I am not signed into the Framework app. I have a Core controller that has an [Authorize] attribute; when I am logged into the Framework app, the page displays just fine, but when I am not logged in, instead of being redirected to the login page, I get the following exception (this is actually from a logfile, but the same thing is also displayed in the browser):

```
2022-09-08 16:32:05 [13] ERROR DeveloperExceptionPageMiddleware.?():? - An unhandled exception has occurred while executing the request.
System.ArgumentException: An item with the same key has already been added. Key:                                 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Security.Claims.Claim..ctor(BinaryReader reader, ClaimsIdentity subject)
   at System.Security.Claims.ClaimsIdentity.CreateClaim(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity.Initialize(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity..ctor(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity.Initialize(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity..ctor(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity.Initialize(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity..ctor(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity.Initialize(BinaryReader reader)
   at System.Security.Claims.ClaimsIdentity..ctor(BinaryReader reader)
   at System.Security.Claims.ClaimsPrincipal.CreateClaimsIdentity(BinaryReader reader)
   at System.Security.Claims.ClaimsPrincipal..ctor(BinaryReader reader)
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationResultFactory.CreateRemoteAppAuthenticationResultAsync(HttpResponseMessage response, RemoteAppAuthenticationClientOptions options)
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationService.AuthenticateAsync(HttpRequest originalRequest, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler.GetRemoteAppAuthenticationResultAsync()
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

The relevant code is in RemoteAppAuthenticationResultFactory:

```
        // If the result has a 200 status code, attempt to deserialize the ClaimsPrincipal
        if (response.StatusCode == HttpStatusCode.OK)
        {
            using var responseContent = await response.Content.ReadAsStreamAsync();
            using var reader = new BinaryReader(responseContent);
            ret = new RemoteAppAuthenticationResult(new ClaimsPrincipal(reader), (int)response.StatusCode, response.RequestMessage);
        }

        // If the remote authentication result hasn't yet been created, create it without a claims principal
        if (ret is null)
        {
            ret = new RemoteAppAuthenticationResult(null, (int)response.StatusCode, response.RequestMessage);
        }
```

This seems to tie into the stacktrace i.e. it is trying to put together the ClaimsPrincipal from the 200 response. However, having managed to get Fiddler to intercept the requests, I can see that the call to the authenticate method is returning a 302, not a 200:

_This is the request to the controller which ultimately returns the error:_
GET http://localhost:8080/R4NNR/Blazor/Userinfo
500 Internal Server Error (text/html)

_Before the error is returned, this results in this authenticate request which returns a 302:_
GET http://healthdev22-pd/R4NNR/systemweb-adapters/authenticate?original-url=%2FR4NNR%2FBlazor%2FUserinfo
302 Redirect to http://localhost:8080/R4NNR/NNR/SignIn?ReturnUrl=%2FR4NNR%2Fsystemweb-adapters%2Fauthenticate%3Foriginal-url%3D%252FR4NNR%252FBlazor%252FUserinfo

_Not really sure what is making this request - doesn't appear to be the browser looking at the dev tools:_
GET http://localhost:8080/R4NNR/NNR/SignIn?ReturnUrl=%2FR4NNR%2Fsystemweb-adapters%2Fauthenticate%3Foriginal-url%3D%252FR4NNR%252FBlazor%252FUserinfo
200 OK (text/html)

I am using nightly build 1.0.0-rc.1.22455.1. My Core app is a new .NET 6 Blazor Server app, and the Framework app is running MVC 5.2.7. I do have a slightly quirky setup, in that I am using an external load balancer rather than running YARP in the Core app - I previously ran into problems with Blazor routing when I tried to use YARP in the actual project. Also, my Framework app did not previously use ASP.NET Identity (we had rolled our own security), but I have followed these [instructions](https://weblog.west-wind.com/posts/2015/Apr/29/Adding-minimal-OWIN-Identity-Authentication-to-an-Existing-ASPNET-MVC-Application) to enable OWIN in the app, which I think is working as expected i.e. the authentication cookie is created properly when I log in.

Feels like I am so close to having this working, but am stuck with this error. Any help appreciated.

**Comment by mjrousos** [comment]
Thanks, @pdunkerley, for reporting the issue. Based on the call stack, it seems like the ASP.NET Core app is having trouble deserializing the ClaimsPrincipal returned by the ASP.NET app. Are you able to provide more details about the identity object your ASP.NET app is using? Can you share an example list of claims (with anything sensitive redacted, of course)?

We've talked about making this process (serializing and deserializing identity) replaceable by abstracting it behind an interface. This sort of issue might be a good motivation to do that. Then you could provide whatever logic you need for the identity objects your auth system produces.

**Comment by pdunkerley** [comment]
Thanks for your reply @mjrousos.

Here is how I have set up the ASP.NET side (based on Rick Strahl's blog that I referenced in my previous post):

Startup.cs
```
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);
        }

        public void ConfigureAuth(IAppBuilder app)
        {
            // Enable the application to use a cookie to store information for the signed in user
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/NNR/SignIn")
            });

            app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
        }
    }
```

This is the code in my sign in controller that gets called after I have successfully logged the user in via my own methods:

```
        private void IdentitySignin(LoggedInUser loggedInUser, bool isPersistent = false)
        {
            var claims = new List<Claim>();

            // create required claims
            claims.Add(new Claim(ClaimTypes.NameIdentifier, loggedInUser.Id.ToString()));
            claims.Add(new Claim(ClaimTypes.Name, loggedInUser.Username));

            var identity = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);

            AuthenticationManager.SignIn(new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = isPersistent,
                ExpiresUtc = DateTime.UtcNow.AddDays(7)
            }, identity);
        }

        private IAuthenticationManager AuthenticationManager => HttpContext.GetOwinContext().Authentication;

```

I can see this is working in so far as it creates the cookie (can see it in browser dev tools), and the Core app can see the User.Identity in a view and list the claims **as long as I have first logged into the Framework app**. It's only when I am not logged in that I have the issues, and at that point, would the Framework app even be returning a ClaimsIdentity? I have a sample app I created from following one of your [tutorials](https://devblogs.microsoft.com/dotnet/incremental-asp-net-migration-tooling-preview-2/); using that app, I can see that when I am not signed in, there is no cookie - does that mean there is no ClaimsIdentity?

Being able to provide a custom method on the Framework side to handle the creation of the ClaimsIdentity would be very useful - I would then not have to use Owin just to create the cookie. Would like to see that feature added.

**Comment by mjrousos** [comment]
@pdunkerley, thanks for the additional information. The fact that this only happens when the user is *not* logged in is very interesting. 

When the app tries to authenticate a user on the ASP.NET Core side, an HTTP request is sent to a dedicated endpoint on the ASP.NET app to retrieve the user's identity. The response from that backchannel request is processed by [`RemoteAppAuthenticationResultFactory`](https://github.com/dotnet/systemweb-adapters/blob/main/src/Microsoft.AspNetCore.SystemWebAdapters.CoreServices/Authentication/RemoteAppAuthenticationResultFactory.cs#L35). That type will look at the status code of the response and, if the status code is 200, it will attempt to deserialize the response body as claims. If the status code is not 200, it will forward the status code and auth-relevant response headers to the original caller.

The fact that this scenario works for you when the user is logged in means that the positive case is working, but the fact that it fails when *not* logged in means that the result factory is trying (and failing) to deserialize claims in that case which should only happen if the remote authentication endpoint is returning 200.

I think there are two possibilities here:

1. Your ASP.NET app returns a 200 response when authentication fails which is confusing the remote app authentication handler in the ASP.NET Core app. If this is the case, can you share more details about the response your ASP.NET app returns when authentication is challenged and no user is logged in? What status code is returned? What headers? 
2. Your ASP.NET app is not recognizing the request from the ASP.NET Core remote app auth handler as being unauthenticated. Is it possible that your custom authentication logic is for some reason treating the request to the new /authenticate endpoint as authenticated when it isn't and returning an odd set of claims that aren't deserializable?

If you can provide some more details on what response is expected from the ASP.NET app when authentication fails, that would be helpful. In the meantime, I will update the remote app authentication solution to be more extensible so that you can provide your own claims deserialization logic and/or debug through what's happening when the response from the ASP.NET app is processed.

**Comment by mjrousos** [comment]
@pdunkerley, looking at this issue again, I have a theory about what could be happening. 

To summarize what we know so far: 

The problem seems to be that when the ASP.NET Core app's `RemoteAppAuthenticationResultFactory` makes a request to the ASP.NET app's */systemweb-adapters/authenticate* endpoint, it assumes that getting back a 200 status code means that there's a serialized `ClaimsPrincipal` in the body.

In your case, though, for some reason, the /authenticate call is returning 200 when the user isn't logged in! If we can figure out why that is, we can solve the problem. Maybe it's because the 302 result from /authenticate (which is expected) is somehow being followed and redirected to the login page (which, of course, returns 200)?

This shouldn't happen because the HttpClient used by `RemoteAppAuthenticationService` should have an HttpClientHandler with `AllowAutoRedirect` set to false. In your case, it seems as if that isn't set, though.

**Can you check to see if you are providing a custom BackchannelHandler or HttpClient on `RemoteAppClientOptions`?** 

If you are (and you haven't set `AllowAutoRedirect` to false), that could explain this issue.

**Comment by danroth27** [comment]
No response for a while, so closing.

**Comment by zachrybaker** [comment]
@mjrousos, @danroth27, Is it possible to reopen this one?
I have the same behavior @pdunkerley was troubleshooting (redirects die/fail without authenticating first by visiting old URL for authentication), but with a slightly different setup, and highly motivated to solve it.

## (A) ASP.NET web forms app, pre-system web adapters:
* http://localhost:3552
* Auth: forms. Login page is ssoLogin.aspx, It redirects to a 3rd site for SSO which redirects back after authentication to webforms app (to ssoLogin.aspx). This time the webforms app sees the authenticated user data, and creates a FormsAuthenticationTicket (cookie), then redirects back to yet another second/different user page (ssoUser.aspx) to match the SSO identity to an app ID - they may have more than one AppUser Id and if so they must choose on this page. With the AppUser Id determined, FormsAuthentication.RedirectFromLoginPage(AppUserId, false); was used to update the User.Identity.Name with the app id and then return to the original URL.  A bit hacky to swap out the type of identity, as the author noted, but it worked.
* Uses a gutted customized ASP.NET membership provider, 
* Standard Session provider (in-proc), 
* Standard Profile provider.

## (A') ASP.NET app, updated with system web adapters-integrated:
* same url, http://localhost:3552
* Auth modifications: Keep the SSO scheme. FormsAuthenticationTicket swapped for a list of claims that include the SSO id, an empty AppId, the session ID (explained below), role, put into a Forms ClaimsIdentity, made into a SessionSecurityToken of the ClaimsPrincipal,  I use the <b>FederatedAuthentication.SessionAuthenticationModule</b> to write the token to cookie.  The SSO and appUser Id sequence still happens, then the claims are updated for the actual AppId and the cookie written to again.  Finally the user is redirected to the originally-requested URL.
* AddSystemWebAdapters with proxy support, AddRemoteAppServer (key and keyheader set), and AddAuthenticationServer (default options).
* Membership provider left alone, 
* Session provider swapped for a custom flavor of the Redis-backed session state provider (to pub-sub a JSON session object so that it can be synced to a Blazor app), 
* Profile provider replaced with a custom profile provider that also pub/subs to Redis to also sync with Blazor app. The provider actually uses Grpc across named pipes to a profile service (that happens to be running under the Blazor app process) to provide initial data from SQL and sync via Redis.

## (B) BLAZOR SERVER, net8.0
* httpS://localhost:7207
* YARP set up with a catch-all to the web forms app at its address.
* use of AddCascadingAuthenticationState in app startup
* AddSystemWebAdapters with AddRemoteAppClient (with RemoteAppUrl, ApiKey and ApiKeyHeader appropriately set), as well as AddAuthenticationClient(true)

## result:
As long as the original app address is hit first, to cause the auth sequence on its domain, everything works fine.
I can have a tab for each application open, and see the cookies for ASP.NET_SessionId and FedAuth magically appear/update in the blazor app's cookie storage when the web forms app sets them.  Not a problem there. Once auth is set, features in either app are faithfully served via the blazor's app url, so proxying seems content.

The problem is that the authentication sequence fails in the new app. Excerpts from what I see in the logs below.

## Logs
 [INF] Request starting HTTP/2 GET https://localhost:7207/ - null null
 [DBG] 3 candidate(s) found for the request path '/'
 [DBG] Endpoint 'Blazor /' with route pattern '/' is valid for the request path '/'
 [DBG] Endpoint '/_Host' with route pattern '' is valid for the request path '/'
 [DBG] Endpoint 'fallbackRoute' with route pattern '{**catch-all}' is valid for the request path '/'
 [DBG] Request matched endpoint '/_Host'
 [DBG] Received remote authentication response with status code "Found"
 [DBG] Remote service did not authenticate a user
 [DBG] AuthenticationScheme: Remote was not authenticated.
 [DBG] Policy authentication schemes  did not succeed
 [INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
 [INF] AuthenticationScheme: Remote was challenged.
 [INF] HTTP GET / RequestBody:


Responded in 14.4330 ms with 302:
 [INF] Request finished HTTP/2 GET https://localhost:7207/ - 302 0 null 16.4005ms
 [INF] Request starting HTTP/2 GET https://localhost:7207/ssoLogin.aspx?ReturnUrl=%2fsystemweb-adapters%2fauthenticate%3foriginal-url%3d%252F&original-url=%2F - null null
 [DBG] 1 candidate(s) found for the request path '/ssoLogin.aspx'
 [DBG] Endpoint 'fallbackRoute' with route pattern '{**catch-all}' is valid for the request path '/ssoLogin.aspx'
 [DBG] Request matched endpoint 'fallbackRoute'
 [DBG] Received remote authentication response with status code "Found"
 [DBG] Remote service did not authenticate a user
 [DBG] AuthenticationScheme: Remote was not authenticated.
 [DBG] Policy authentication schemes  did not succeed
 [INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
 [INF] AuthenticationScheme: Remote was challenged.
 [INF] HTTP GET /ssoLogin.aspx?ReturnUrl=%2fsystemweb-adapters%2fauthenticate%3foriginal-url%3d%252F&original-url=%2F RequestBody:


Responded in 6.4224 ms with 302:
 [INF] Request finished HTTP/2 GET https://localhost:7207/ssoLogin.aspx?ReturnUrl=%2fsystemweb-adapters%2fauthenticate%3foriginal-url%3d%252F&original-url=%2F - 302 0 null 8.1477ms
 [INF] Request starting HTTP/2 GET https://localhost:7207/ssoLogin.aspx?ReturnUrl=%2fsystemweb-adapters%2fauthenticate%3foriginal-url%3d%252FssoLogin.aspx%253FReturnUrl%253D%25252fsystemweb-adapters%25252fauthenticate%25253foriginal-url%25253d%2525252F%2526original-url%253D%25252F&original-url=%2FssoLogin.aspx%3FReturnUrl%3D%252fsystemweb-adapters%252fauthenticate%253foriginal-url%253d%25252F%26original-url%3D%252F - null null
...(another round trip, with a 302)...
 [INF] Request finished HTTP/2 GET https://localhost:7207/ssoLogin.aspx?ReturnUrl=%2fsystemweb-adapters%2fauthenticate%3foriginal-url%3d%252FssoLogin.aspx%253FReturnUrl%253D%25252fsystemweb-adapters%25252fauthenticate%25253foriginal-url%25253d%2525252F%2526original-url%253D%25252F&original-url=%2FssoLogin.aspx%3FReturnUrl%3D%252fsystemweb-adapters%252fauthenticate%253foriginal-url%253d%25252F%26original-url%3D%252F - 302 0 null 7.5173ms
 [INF] Request starting HTTP/2 GET https://localhost:7207/ssoLogin.aspx?ReturnUrl=%2fsystemweb-adapters%2fauthenticate%3foriginal-url%3d%252FssoLogin.aspx%253FReturnUrl%253D%25252fsystemweb-adapters%25252fauthenticate%25253foriginal-url%25253d%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252F%25252526original-url%2525253D%252525252F%2526original-url%253D%25252FssoLogin.aspx%25253FReturnUrl%25253D%2525252fsystemweb-adapters%2525252fauthenticate%2525253foriginal-url%2525253d%252525252F%252526original-url%25253D%2525252F&original-url=%2FssoLogin.aspx%3FReturnUrl%3D%252fsystemweb-adapters%252fauthenticate%253foriginal-url%253d%25252FssoLogin.aspx%25253FReturnUrl%25253D%2525252fsystemweb-adapters%2525252fauthenticate%2525253foriginal-url%2525253d%252525252F%252526original-url%25253D%2525252F%26original-url%3D%252FssoLogin.aspx%253FReturnUrl%253D%25252fsystemweb-adapters%25252fauthenticate%25253foriginal-url%25253d%2525252F%2526original-url%253D%25252F - null null
(one or two more 302's, the url growing, until finally a 404)
 [INF] Request starting HTTP/2 GET https://localhost:7207/ssoLogin.aspx?ReturnUrl=%2fsystemweb-adapters%2fauthenticate%3foriginal-url%3d%252FssoLogin.aspx%253FReturnUrl%253D%25252fsystemweb-adapters%25252fauthenticate%25253foriginal-url%25253d%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252FssoLogin.aspx%25252525253FReturnUrl%25252525253D%2525252525252fsystemweb-adapters%2525252525252fauthenticate%2525252525253foriginal-url%2525252525253d%252525252525252F%252525252526original-url%25252525253D%2525252525252F%25252526original-url%2525253D%252525252FssoLogin.aspx%252525253FReturnUrl%252525253D%25252525252fsystemweb-adapters%25252525252fauthenticate%25252525253foriginal-url%25252525253d%2525252525252F%2525252526original-url%252525253D%25252525252F%2526original-url%253D%25252FssoLogin.aspx%25253FReturnUrl%25253D%2525252fsystemweb-adapters%2525252fauthenticate%2525253foriginal-url%2525253d%252525252FssoLogin.aspx%252525253FReturnUrl%252525253D%25252525252fsystemweb-adapters%25252525252fauthenticate%25252525253foriginal-url%25252525253d%2525252525252F%2525252526original-url%252525253D%25252525252F%252526original-url%25253D%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252F%25252526original-url%2525253D%252525252F&original-url=%2FssoLogin.aspx%3FReturnUrl%3D%252fsystemweb-adapters%252fauthenticate%253foriginal-url%253d%25252FssoLogin.aspx%25253FReturnUrl%25253D%2525252fsystemweb-adapters%2525252fauthenticate%2525253foriginal-url%2525253d%252525252FssoLogin.aspx%252525253FReturnUrl%252525253D%25252525252fsystemweb-adapters%25252525252fauthenticate%25252525253foriginal-url%25252525253d%2525252525252F%2525252526original-url%252525253D%25252525252F%252526original-url%25253D%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252F%25252526original-url%2525253D%252525252F%26original-url%3D%252FssoLogin.aspx%253FReturnUrl%253D%25252fsystemweb-adapters%25252fauthenticate%25253foriginal-url%25253d%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252F%25252526original-url%2525253D%252525252F%2526original-url%253D%25252FssoLogin.aspx%25253FReturnUrl%25253D%2525252fsystemweb-adapters%2525252fauthenticate%2525253foriginal-url%2525253d%252525252F%252526original-url%25253D%2525252F - null null
 [INF] HTTP GET /ssoLogin.aspx?ReturnUrl=%2fsystemweb-adapters%2fauthenticate%3foriginal-url%3d%252FssoLogin.aspx%253FReturnUrl%253D%25252fsystemweb-adapters%25252fauthenticate%25253foriginal-url%25253d%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252FssoLogin.aspx%25252525253FReturnUrl%25252525253D%2525252525252fsystemweb-adapters%2525252525252fauthenticate%2525252525253foriginal-url%2525252525253d%252525252525252F%252525252526original-url%25252525253D%2525252525252F%25252526original-url%2525253D%252525252FssoLogin.aspx%252525253FReturnUrl%252525253D%25252525252fsystemweb-adapters%25252525252fauthenticate%25252525253foriginal-url%25252525253d%2525252525252F%2525252526original-url%252525253D%25252525252F%2526original-url%253D%25252FssoLogin.aspx%25253FReturnUrl%25253D%2525252fsystemweb-adapters%2525252fauthenticate%2525253foriginal-url%2525253d%252525252FssoLogin.aspx%252525253FReturnUrl%252525253D%25252525252fsystemweb-adapters%25252525252fauthenticate%25252525253foriginal-url%25252525253d%2525252525252F%2525252526original-url%252525253D%25252525252F%252526original-url%25253D%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252F%25252526original-url%2525253D%252525252F&original-url=%2FssoLogin.aspx%3FReturnUrl%3D%252fsystemweb-adapters%252fauthenticate%253foriginal-url%253d%25252FssoLogin.aspx%25253FReturnUrl%25253D%2525252fsystemweb-adapters%2525252fauthenticate%2525253foriginal-url%2525253d%252525252FssoLogin.aspx%252525253FReturnUrl%252525253D%25252525252fsystemweb-adapters%25252525252fauthenticate%25252525253foriginal-url%25252525253d%2525252525252F%2525252526original-url%252525253D%25252525252F%252526original-url%25253D%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252F%25252526original-url%2525253D%252525252F%26original-url%3D%252FssoLogin.aspx%253FReturnUrl%253D%25252fsystemweb-adapters%25252fauthenticate%25253foriginal-url%25253d%2525252FssoLogin.aspx%2525253FReturnUrl%2525253D%252525252fsystemweb-adapters%252525252fauthenticate%252525253foriginal-url%252525253d%25252525252F%25252526original-url%2525253D%252525252F%2526original-url%253D%25252FssoLogin.aspx%25253FReturnUrl%25253D%2525252fsystemweb-adapters%2525252fauthenticate%2525253foriginal-url%2525253d%252525252F%252526original-url%25253D%2525252F RequestBody:


Responded in 5.2909 ms with 404:
and, comically, it looks for favicon.ico, which doesn't exist in either app but YARP and web.config trigger an auth redirect loop for it as well...

I am hoping there is a solution/resolution here. The FedAuth approach to get claims in place seemed necessary to carry the session id to the circut to bootstrap the session subscription on the blazor side.
