### ISSUE TITLE
API changes for rc1: documentation and blogpost examples don't compile

### ISSUE THREAD

**Issue by tbertenshaw** [dotnet/systemweb-adapters#214]
Updated documentation for Rc1 seems syntactically incorrect.

I'm using remote authentication.

The initial [blogpost  ](https://devblogs.microsoft.com/dotnet/migrating-from-asp-net-to-asp-net-core-part-4/) references 
`AddJsonSessionKeySerializer`
 Intellisense doesn't recognise this method but does like `AddJsonSessionSerializer`. Is this the correct method?

Also in [remote auth documentation](https://github.com/dotnet/systemweb-adapters/blob/main/docs/remote-authentication/remote-authentication.md) 

```csharp
builder.Services.AddSystemWebAdapters()
    .AddRemoteApp(options =>
    {
        options.RemoteAppUrl = new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
        options.ApiKey = builder.Configuration("RemoteAppApiKey");
    })
    .AddRemoteAppAuthentication(true);
```
I get intellisense errors for `AddRemoteAppAuthentication`.

Have these documents been updated since the api changes?

**Comment by tbertenshaw** [comment]
Seems also to be another dependancy issue :(
![image](https://user-images.githubusercontent.com/2010002/193413124-ee4e8623-8e5d-4eb3-9a6c-b127bdb3f4bb.png)

**Comment by twsouthwick** [comment]
@tbertenshaw Looks like a couple of issues here:

1. `AddJsonSessionSerializer` is what you want
2. `AddRemoteApp` should be `AddRemoteAppClient`

The docs were updated, but apparently some got an interim fix instead of the final. I'll leave this open to identify that.

> Seems also to be the start of another dependency hell issue :( ![image](https://user-images.githubusercontent.com/2010002/193413124-ee4e8623-8e5d-4eb3-9a6c-b127bdb3f4bb.png)

This warning is saying you are referencing 4.6.0 directly of the library, but we're referencing v6.0.0 indirectly. You can either remove your reference, or update your reference to 6.0.0
