### ISSUE TITLE
Error reporting when serialization an unknown session key

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#32]
## Summary

When serializing session, we require keys to be registered with the type they represent. However, people will probably not know the keys they have and will need a way to identify that. The simplest would be to turn on some messaging around keys that aren't registered. This issue is to decide on how we want to do that.

This will focus on the scenario where we have remote app session state enabled.

## Reproduce

Create a remote app session without registering known keys. Attempt to load session on core side. An `InvalidOperationException` is thrown at the point of serializing an unknown key.

- When serializing/deserializing on the framework side, this leads to a 500 error on the framework handler, which propagates down to the core app as a failure. There is no actionable message available here.
- If the framework side has successfully serialized a payload (it knows about all the keys), but the core app encounters a key it is unaware of, it will surface as a `InvalidOperationException` that causes the request to fail. Same thing occurs if a key is added that is unknown when we attempt to serialize. 

### Option 1

This option still causes the request to fail, but attempts to provide the information to mitigate it.

```csharp
public class UnknownSessionKeyException
{
  public IReadOnlyCollection<string> UnknownKeys { get; }
}
```

- The request to the framework app should not result in a 500 error. Instead, it should provide a https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails object that lists the unknown keys
- Upon error from the framework app, the core app will raise an UnknownSessionKeyException which lists all the unknown keys
- Upon deserialization/serialization attempt, the session middleware will raise an UnknownSessionKeyException if an unknown key is encountered
- This will still cause a failure of the request on the ASP.NET Core side, but will provide a list of unknown keys

### Option 2

This option will not fail if an unknown key is found, but will log error messages that clearly identify the unknown keys.

- The request to the framework app should not result in a 500 error. If an unknown key is found, it should be added to the payload as a new field that will convey that information to the client.
- When the core app receives its payload, it will right out a message of the unknown keys at an Error level to communicate to the developer that a key was used that has not been registered
- When the session middleware serializes the new keys, it will write out any unknown keys to the log

### Option 3

A combination of Option 1 and Option 3 that can be opted into via the Session options

## Additional thoughts

- Do we want to include the type info of the key that was found if attempting to serialize and it's not registered?

**Comment by mjrousos** [comment]
I prefer defaulting to failing in because I think it will be an easy mistake to make and failing the request with a good error message is probably the surest way to make sure users know they've done something wrong (and what they need to do about it).

That said, I also like the idea of making this configurable since there could be scenarios where users know that the server session state has a lot of items but only a few will be interesting to the ASP.NET Core endpoints and they don't want to bother registering all of them initially.

More tactically, I don't have a strong opinion about whether option 1 or a version of option 2 that fails by default is better. Off the top of my head, it seems like some variant of 2 that has the ASP.NET app just return data about missing keys to the Core app and have the Core app always be responsible for failing (or not, depending on configuration) may be a good way to go since it would be easier to centralize some of the logic around deciding whether to fail or log, etc. Whichever way is easiest to implement and maintain in practice, though, is likely fine.
