### ISSUE TITLE
Support for UrlHelper methods during incremental migration

### ISSUE THREAD

**Issue by dlumpp** [dotnet/systemweb-adapters#355]
Are there any plans to support UrlHelpers like the Action method during an incremental migration? 

Currently, when I migrate a controller and route to the new web app, any Url.Action calls for that route in the old web app could potentially generate the wrong URL. Similarly, the new app's UrlHelper won't know anything about the old app's unmigrated routes.

My specific case is building links for a navigation menu and the only solution would be to Ctrl+F for usages and hard-code the correct action name.

**Comment by psicus78** [comment]
It would be fine if there was a way to set the base url of the old appllication in a way that all the created urls will be pointing to the new webapp.

**Comment by twsouthwick** [comment]
Can you share what you're currently doing and what you would like? A sample app would be helpful.

**Comment by dlumpp** [comment]
Let me describe the specific situation I ran into. This is only a problem when deviating from controller-based route naming conventions. 

The remote (old) app has a controller like this, that has had an action name changed via attribute:
```cs
public class FullCatalogController 
{
  [Route("~/Shop")]
  public ActionResult Index() {}
}
```
The nav bar links to that page using `Url.Action("Index", "FullCatalog")` in Razor, which writes `/Shop`.


After migrating this controller to the new (ASP.NET Core) app, the old app has no awareness of the route attribute. Now my existing `Url.Action("Index", "FullCatalog")` call in the old Razor writes `/FullCatalog` which doesn't exist.

**Comment by joperezr** [comment]
[Triage] If we are understanding correctly, then you want the Razor code which lives in the old app to use URLHelper to automatically re-route you to a controller on the new app? If so, then this is not something we think we can support. The advice there would be to either fix the links in the Razor code so that they point to the right route so that the right controller receives the request (meaning changing UrlAction to point to the `Shop` endpoint, or alternatively you can keep a copy of the controller in the old app which works as a re-router so that the right controller from the new app is called.
