### ISSUE TITLE
Simplify registration of remote app urls

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#50]
For things like remote app session, we require setting up the remote app. This is currently being done by digging into the same config value that YARP is using:

```csharp
builder.Services.AddSystemWebAdapters()
    .AddRemoteAppSession(options =>
    {
        // Provide the URL for the remote app that has enabled session querying
        options.RemoteApp = new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);

        // Provide a strong API key that will be used to authenticate the request on the remote app for querying the session
        options.ApiKey = "strong-api-key";
    });
```

This looks a little ugly - can we refine this at all?

**Comment by davidfowl** [comment]
Also RemoteApp and ApiKey exist on both session and auth, maybe those should be consolidated?

**Comment by twsouthwick** [comment]
I believe @mjrousos is handling that as part of his auth implementation.

**Comment by mjrousos** [comment]
Sort of. This is a tricky one because on the one hand it feels really weird to set these same values multiple times but, on the other hand, it also feels weird to configure things like ApiKey and RemoteAppUrl in core SystemWebAdapter configuration when those values aren't actually needed there (they're only needed for additional features like session sharing or auth sharing that users can opt into).

The way I've handled this in the auth PR is that I still require both session and auth configuration to set RemoteAppUrl and ApiKey, but I have both options types derive from a common base type with these properties so users can at least have code that sets these properties shared between both auth and session configuration.

I'm still not entirely happy with the solution but it's better than nothing. The alternative would be to just bake the concept of RemoteAppUrl and ApiKey into SystemWebAdapter options even though they aren't used there.

**Comment by twsouthwick** [comment]
What about keeping it separate, but as a general remote app:

```csharp
builder.Services.AddSystemWebAdapters(options =>
    {
    })
    .AddJsonSessionSerializer(options => RegisterSessionKeys(options))
    .AddRemoteApp(options =>
   {
        options.RemoteAppUrl = new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
        options.ApiKey = "strong-api-key";
   })
    .AddRemoteAppSession()
    .AddRemoteAppAuthentication();
```

And that would get plumbed through as an `IOptions<RemoteAppOptions>`:

```csharp
public class RemoteAppOptions
{
  public Uri RemoteAppUrl { get; set; }
  public string ApiKey { get; set; }
}
```

We could potentially use named options to disambiguate if people want multiple, but I don't see that as a required scenario at the moment.

**Comment by mjrousos** [comment]
I like that option. It's not that different from just setting those options in SystemWebAdapters options directly, but it seems good to have remote app stuff separated out to keep things clear. I'll update things to work this way.
