### ISSUE TITLE
 Confused about how to use Microsoft.AspNetCore.SystemWebAdapters while trying to port from old ASP.NET website to new ASP.NET Core web app

### ISSUE THREAD

**Issue by sameerranade** [dotnet/systemweb-adapters#506]
https://stackoverflow.com/questions/78589165/confused-about-how-to-use-microsoft-aspnetcore-systemwebadapters-while-trying-to?noredirect=1#comment138554749_78589165

Can someone please answer my question on Stackoverflow? I am not sure what exactly needs to be done in my case. Are the adapter classes provided by SystemWebAdapters?

**Comment by twsouthwick** [comment]
Did you see the docs here: https://learn.microsoft.com/en-us/aspnet/core/migration/inc/overview?view=aspnetcore-8.0?

Looks like you already got a great answer from someone there that I can't add much to. We have some samples in this repo that show a few examples of features.

The main thing to think about when using this is if instead of referencing `System.Web` you reference `Microsoft.AspNetCore.SystemWebAdapters` it'll allow for multi-targeted (or .net standard 2.0) builds of supported APIs. If you are using APIs that don't exist in this project, then you'll have to either polyfill them yourself or start a discussion here. If you find APIs that you implement for System.Web, we welcome contributions.

I'm going to close this as it appears to be answered on Stackoverflow. Please feel free to open new issues for missing APIs
