### ISSUE TITLE
A 407 Proxy Authentication Required when using remote authentication

### ISSUE THREAD

**Issue by TheJayMann** [dotnet/systemweb-adapters#72]
### Describe the bug
When using the remote authentication which was included in a recent update, after the authentication is complete, when the `/systemweb-adapters/authenticate` endpoint is loaded, an IIS HTTP 407.0 Proxy Authentication Required page is displayed.  After this error page is loaded, any attempt to go to any URL, whether it ends up loading the new ASP.NET Core application, or if it loads the old ASP.NET application, works without any further issues, with the user properly authenticated.  Also, the Logon User field on the error page does properly list the username of the person logged in.

This application is not using forms authentication nor bearer jwt.  It is instead making use of the `WsFederationAuthenticationModule` and `SessionAuthenticationModule` to allow federated login.  As I have it set up, the original ASP.NET application ran on localhost:44378, and the STS is set up to post the token to localhost:44378/, which would be processed by the `WsFederationAuthenticationModule`.  After the migration, the new ASP.NET Core application runs on localhost:44395.  When a challenge occurs, a redirect to the STS with the proper WS-Federation supplied information does occur, I am able to log in via the STS, and it posts the data to localhost:44378/, which properly processes the token, and then redirects to localhost:44378/systemweb-adapters/authenticate, at which point the Proxy Authentication Required page appears.  Attempting to reload localhost:44395 works with the logged in user information available.

I also attempted changing the STS to post the token information to localhost:44395/signin-wsfed (in order to make sure the request gets properly forwarded to the ASP.NET application rather than being handled by the default razor page in ASP.NET Core), the result is exactly the same, with the exception that the Proxy Authentication Required page is loaded from localhost:44395/systemweb-adapters/authenticate.  Also, just like before, reloading localhost:44395 after this results in proper authenticated access.

I do not have enough information to determine if this issue is caused by trying to use this with `WsFederationAuthenticationModule`, or if this is due to having something else not set up properly.

### To Reproduce
After performing a migration via the VS extension and then updating the SystemWebAdapters package to a locally built package containing the remote authentication implementation, I added code to enable the remote authentication.

ASP.NET Core application
```csharp
    .AddRemoteAppAuthentication(true, opts => {
        opts.RemoteServiceOptions.ApiKey = "Some secret key";
        opts.RemoteServiceOptions.RemoteAppUrl = 
            new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"])
        ;
    })
```
ASP.NET Application
```csharp
    .AddProxySupport(opts => {
        opts.UseForwardedHeaders = true;
    })
    .AddRemoteAppAuthentication(opts => {
        opts.RemoteServiceOptions.ApiKey = "Some secret key";
    })
```

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): WebForms
- .NET Framework Version: 4.7.2
- IIS Version: 10 Express
- Windows Version: 10

*ASP.NET Core Application*:
- Targeted .NET version: 6.0
- .NET SDK version: 6.0.300

**Comment by mjrousos** [comment]
Thanks for reporting this, @TheJayMann. It looks like the shared auth support isn't working quite right with WS-Fed auth. `/systemweb-adapters/authenticate` is the endpoint that serves authentication information from the ASP.NET app (the ASP.NET Core app will call it from its remote app auth handler) but users shouldn't be re-directed back to that URL (since, as you've discovered, it will fail with 407 for any requests not coming from the ASP.NET Core app).

For other auth scenarios (ASP.NET Identity cookie auth), there's logic in the auth handler to actually intercept redirects to /systemweb-adapters/authenticate and rewrite them. It seems that isn't working for the WS-Fed scenario, though. Probably it's because the auth process actually redirects away from the site entirely and when the STS redirects back the 'redirect back to' URL it was given is /systemweb-adapters/authenticate and the result processor that usually fixes up redirects won't apply.

I've got some ideas of how we might be able to solve this. One option would be to include the "real" re-direct URI in a query string when calling /systemweb-adapters/authenticate and then look for that when the redirect comes back. Whether that works or not would depend on whether or not query strings persist through auth and redirection. Another option would be to just allow users to configure a URL that should be used instead if an auth process tries to redirect to /systemweb-adapters/authenticate.

I'll investigate this week and report back with what I find and which options seem the most promising.

**Comment by mjrousos** [comment]
It looks like OIDC cookie scenarios (like using AAD B2C from an MVC app) has a similar problem, which is nice since that's an easier scenario to repro (no need to set up an STS). It seems the common thing that doesn't work well is the flow of the ASP.NET app having to redirect to an external site for authentication and then handle a redirect when auth is complete. I'll work on getting a fix together.

**Comment by TheJayMann** [comment]
Testing this with WS-Federation shows that the issue has been resolved.
